### PR TITLE
Support gradle multi-project

### PR DESCRIPTION
**Pull request by civitaspo**
Signed-off-by: civitaspo <civitaspo@gmail.com>

Fix https://github.com/github/licensed/issues/301

This PR supports gradle projects with multi-project configuration. The `settings.gradle` defined in the project was ignored when executing `printDependencies`, which is a task to output dependencies, so it is now used. Running a Gradle Task without `settings.gradle` in a project that defines `settings.gradle` could lead to unintended behavior, so this fix ensures that Gradle Tasks run correctly. Just to make sure that backwards compatibility is not broken, I've tested this on a few projects I manage and found no change in behavior. The support for `build.gradle.kts` and `settings.gradle.kts` written in Kotlin mentioned in https://github.com/github/licensed/issues/301 will be done in the next PR after this PR is merged.

### CODE REVIEW

**Review by jonabc — COMMENTED** [review]
:wave: @civitaspo thanks for opening this!  Is there a way to add or update the Gradle test cases to validate this scenario and prevent regressions in the future?

the code itself makes sense given your PR writeup, ensuring that the code works as expected in the future is my only concern 🙏

**Comment by civitaspo** [comment]
@jonabc I will try to add some test cases. This is going to be a bit of a big pull request as there is currently no code to test the behavior of gradle itself. I'll probably add some gradle projects to the repository for testing.

**Review by jonabc — APPROVED** [review]
@civitaspo is there anything else I should be watching or waiting for related to this PR?  The changes all look good, and I really appreciate the addition of fixtures and tests for a multi-project gradle scenario

**Comment by civitaspo** [comment]
@jonabc Thanks for taking care of it. `Test / gradle (11) (pull_request)` still haven't passed, so I'll need to fix that a bit more. I've been busy with work and haven't had time to fix it, so please wait a little longer.

**Comment by jonabc** [comment]
@civitaspo no problem at all, I'm just checking in from time to time to see how things are going since I don't have much experience in the problem space 😄

**Comment by jonabc** [comment]
closing this PR, multi-project support was implemented in https://github.com/github/licensed/pull/583

**Pull request closed without merging**
